version: "3"
services:
  app:
    image: palindrome_app
    build: .
    ports:
      - "3000:3000"
    command: node server.js
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"